languageCode = "en-us"
title = "Matt Pruitt"
baseurl = "http://mattpruitt.com/"
theme = "hyde"

PygmentsCodeFences = true
pygmentsstyle = "pastie"

[params]
  themeColor = "theme-base-08"
  description = "Elixir. Ruby."

[taxonomies]
  tag = "tags"
